### PR TITLE
Integrate starlark and latest windows version

### PR DESCRIPTION
**Pull request by tboerger**
This is the reference implementation for the plugin org.

### CODE REVIEW

**Comment by appleboy** [comment]
cloud.drone.io support build in windows now?

**Comment by bradrydzewski** [comment]
> cloud.drone.io support build in windows now?

@appleboy drone supports a new type of agent called an ssh agent. The ssh agent executes a pipeline on a remote server that _you_ provide using ssh. The ssh agent supports windows and linux or any posix compliant operating system.

**Comment by appleboy** [comment]
@bradrydzewski Look good. Andy documents about all kind of `type` in drone ?

**Comment by bradrydzewski** [comment]
I have been working on the documentation (on and off) for the past couple of weeks. I am hoping to publish something early next week.

**Comment by tboerger** [comment]
As discussed with brad I will remove the support for windows 1803 as we anyway don't have any runner for it

**Comment by appleboy** [comment]
@tboerger build fail.

**Comment by tboerger** [comment]
This PR is blocked until we got the credentials setup. The generated .drone.yml got to be generated with `drone script --source .drone.starlark --format false`, otherwise the ssh runner credentials are stripped out, we can drop the generated .drone.yml directly after Drone introduces server-side support for starlark.

**Pull request merged**
