### PR TITLE
Load ssh key into the agent so ansible-galaxy picks it up

### PR DESCRIPTION
**Pull request by matijavizintin**
Currently ansible-galaxy install doesn't take into account the PrivateKey parameter and unfortunately it doesn't support --private-key parameter as the ansible command does.

If you have requirements that are fetched from a private repo via ssh and you need to load the private key into the ssh agent. So instead of dumping the private key into a temp file now it is stored into the default location where the ssh agent picks it up.

The PR is related to https://github.com/drone-plugins/drone-ansible/issues/45

### CODE REVIEW

**Review by fbartels — APPROVED** [review]

**Comment by markocelan** [comment]
can we move forward with this?

**Comment by sprnza** [comment]
It's a shame how long it takes for PR to be approved in this project.

**Comment by tphoney** [comment]
Hey folks, sorry for the delay on the review. I am not an ansible expert. but this could have unforseen side affects. 
Particularly if the user has already set up ssh for other things. Is it possible to allow the setting of the key folder as a variable

**Comment by matijavizintin** [comment]
@tphoney You are right, if the user is configuring the ssh key inside the testing container then this setting will be overridden (I'm assuming that plugin is loaded before user's commands are executed). Unfortunately it's not possible to pass the key location to ansible-galaxy and it tries to auth only with what is loaded in the ssh agent.

**Pull request closed without merging**
