### PR TITLE
Bump ansible 2.10.8

### PR DESCRIPTION
**Pull request by guessi**
ansible 2.10.x release note: [link](https://github.com/ansible/ansible/blob/stable-2.10/changelogs/CHANGELOG-v2.10.rst)

### CODE REVIEW

**Comment by tboerger** [comment]
I think it would make more sense to rebuild the plugin based on our plugin lib first. Beside that, generating the drone config in a formatted way breaks the windows builds.

**Comment by guessi** [comment]
interesting 🤔 
it shouldn't have any break after formatting, and I don't see any Windows-related CI/CD pipeline defined in `.drone.yml`

may I ask where's the configuration for Windows builds?

**Comment by guessi** [comment]
@tboerger I've removed the change for `.drone.yml`

plus, after digging the history, found there's a commit for [Dropping Windows Support](https://github.com/drone-plugins/drone-ansible/pull/25), do we really need to support Windows build?

**Comment by androiddrew** [comment]
Yes please, looking forward to this version bump....

**Comment by guessi** [comment]
@tboerger any chance to make some progress?

while we are waiting this version bumping, `ansible` becomes [ansible-4.2.0](https://pypi.org/project/ansible-base/#history), and `ansible-base` becomes [ansible-base-2.10.11](https://pypi.org/project/ansible-base/#history), and [ansible-core](https://pypi.org/project/ansible-core/#history). I'm worry about the breaking changes in the coming ansible releases, according to it's [Q&A](https://www.ansible.com/blog/ansible-3.0.0-qa).

**Comment by guessi** [comment]
Umm... just found another surprise, kind of breaking change,

it's break after bumping `plugins/base` to [alpine3.14](https://github.com/drone-plugins/drone-base/commit/5b3cde5006d0df310ddf880e2a66c307af431f32).

**Comment by tphoney** [comment]
This needs rebased and there looks to be issues with the change. I am closing this for now. 
If someone wants to reopen this and address the issues, we can re-look.

**Pull request closed without merging**
